name: Grok Connect
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'connectors/**'
jobs:
  build:
    name: Build maven
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        working-directory: ./connectors
        run: mvn -Dmaven.test.skip=true package
      - name: Get version
        id: get_version
        working-directory: ./connectors
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          token=$(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:datagrok/grok_connect:pull" | jq --raw-output .token)
          image_status=$(curl -LIs -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${token}" "https://registry.hub.docker.com/v2/datagrok/grok_connect/manifests/${current_version}")
          echo '::echo::on'
          if [[ "${image_status}" == "404" ]] || [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
            echo "::set-output name=version::${current_version}"
          fi
          echo '::echo::off'

  docker:
    name: Build Docker
    needs: build
    if: needs.build.outputs.version != ''
    environment: Prod
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set buildx parameters
        id: param
        run: |
          commit_sha=$(echo ${{ github.sha }} | cut -c1-8)
          branch=$(echo ${GITHUB_REF#refs/heads/})
          echo "::set-output name=commit_sha::${commit_sha}"
          echo "::set-output name=branch::${branch}"
          if [[ ${{ github.ref }} != 'refs/heads/master' ]]; then
            platform='linux/amd64'
            echo "::set-output name=platform::${platform}"
            tar="grok_connect_${{ needs.build.outputs.version }}-$(echo ${platform#linux/})-${commit_sha}-${{ github.run_id }}-${{ github.run_attempt }}.tar"
            echo "::set-output name=tar::${tar}"
            echo "::set-output name=dest::type=docker,dest=/tmp/${tar}"

            platform_add='linux/arm64'
            echo "::set-output name=platform_add::${platform_add}"
            tar_add="grok_connect_${{ needs.build.outputs.version }}-$(echo ${platform_add#linux/})-${commit_sha}-${{ github.run_id }}-${{ github.run_attempt }}.tar"
            echo "::set-output name=tar_add::${tar_add}"
            echo "::set-output name=dest_add::type=docker,dest=/tmp/${tar_add}"
          else
            echo "::set-output name=cache_to::type=registry,ref=datagrok/grok_connect:cache,mode=max"
            echo "::set-output name=platform::linux/amd64,linux/arm64"
          fi

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./connectors/Dockerfile
          failure-threshold: error

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./connectors
          platforms: ${{ steps.param.outputs.platform }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: datagrok/grok_connect:latest,datagrok/grok_connect:${{ needs.build.outputs.version }}
          cache-from: type=registry,ref=datagrok/grok_connect:cache
          cache-to: ${{ steps.param.outputs.cache_to }}
          outputs: ${{ steps.param.outputs.dest }}
          build-args: |
            BRANCH=${{ steps.param.outputs.branch }}
            COMMIT_PUBLIC=${{ github.sha }}
          labels: |
            BRANCH=${{ steps.param.outputs.branch }}
            COMMIT_PUBLIC=${{ github.sha }}

      - name: Upload Artifact
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.param.outputs.tar }}
          path: /tmp/${{ steps.param.outputs.tar }}
          retention-days: 7

      - name: Build and push additional platform
        uses: docker/build-push-action@v3
        if: steps.param.outputs.platform_add != '' && steps.param.outputs.dest_add != ''
        with:
          context: ./connectors
          platforms: ${{ steps.param.outputs.platform_add }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: datagrok/grok_connect:latest,datagrok/grok_connect:${{ needs.build.outputs.version }}
          cache-from: type=registry,ref=datagrok/grok_connect:cache
          cache-to: ${{ steps.param.outputs.cache_to }}
          outputs: ${{ steps.param.outputs.dest_add }}
          build-args: |
            BRANCH=${{ steps.param.outputs.branch }}
            COMMIT_PUBLIC=${{ github.sha }}
          labels: |
            BRANCH=${{ steps.param.outputs.branch }}
            COMMIT_PUBLIC=${{ github.sha }}

      - name: Upload Artifact
        if: github.ref != 'refs/heads/master' && steps.param.outputs.tar_add != ''
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.param.outputs.tar_add }}
          path: /tmp/${{ steps.param.outputs.tar_add }}
          retention-days: 7
